import { FC, ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";

import SmoothScrollProvider from "@/components/providers/smooth-scroll-provider";

import Transition from "@/features/transition";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<IRootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn("font-inter antialiased", inter.variable)}>
        <SmoothScrollProvider>
          <Transition>{children}</Transition>
        </SmoothScrollProvider>
      </body>
    </html>
  );
};

export default RootLayout;
